version: 2
jobs:
  build:
    working_directory: ~/magik-vector
    docker:
      - image: circleci/node:10
    steps:

      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: install dependencies
          command: yarn install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: create directory for test results
          command: |
            mkdir -p ./test-results
            mkdir -p ./test-results/jest

      - run:
          name: lint code
          command: yarn lint

      - run:
          name: test code
          command: yarn test

      - run:
          name: code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'

      - store_artifacts:
          path: test-results.xml
          prefix: tests

      - store_artifacts:
          path: coverage
          prefix: coverage

      - store_test_results:
          path: test-results.xml
