version: 2
jobs:
  build:
    working_directory: ~/magik-vector
    docker:
      - image: circleci/node:10
    steps:

      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: install dependencies
          command: yarn

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: lint code
          command: yarn lint

      - run:
          name: test code
          command: yarn test

      - run:
          name: code coverage
          command: yarn test:coverage:ci

